services:
  courier:
    container_name: courier
    image: ghcr.io/moeux/courier/courier:latest
    restart: unless-stopped

    user: "${UID}:${GID}"

    environment:
      Courier__Bot__Token: ${COURIER_BOT_TOKEN}
      Courier__Bot__FilePath: /app/data/commands
      Courier__Feed__FilePath: /app/data/feeds.json

    volumes:
      - ./data/feeds.json:/app/data/feeds.json
      - ./data/commands:/app/data/commands:ro

    security_opt:
      - no-new-privileges:true

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
