services:
  courier:
    container_name: courier
    image: ghcr.io/moeux/courier/courier:latest
    restart: unless-stopped

    environment:
      Courier__Bot__Token: ${COURIER_BOT_TOKEN}
      Courier__Bot__FilePath: /app/data/commands
      Courier__Feed__FilePath: /app/data/feeds.json

    volumes:
      - type: bind
        source: ./data/feeds.json
        target: /app/data/feeds.json
        read_only: false

      - type: bind
        source: ./data/commands
        target: /app/data/commands
        read_only: true

    read_only: true

    tmpfs:
      - /tmp

    security_opt:
      - no-new-privileges:true

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
